---
- hosts: webservers # Host 
  become: true
  become_user: root
  tasks:
  - name: UnInstall httpd package
    yum: name=httpd state=absent

# Severs Install tomcat
---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Install tomcat package
    yum: name=tomcat state=present
  - name: start tomcat service
    service: name=tomcat state=started
  - name: Deploy sample.war
    copy: src=sample.war dest=/usr/share/tomcat/webapps
    notify: restart handlers
  handlers:
  - name: restart handlers
    service: name=tomcat state=restarted


# Servers install httpd
---
- hosts: webservers
  become: true
  become_user: root
  vars:
   src_path: /etc/ansible
   dest_path: /var/www/html
  tasks:
  - name: Install httpd package
    yum: name=httpd state=present
  - name: start httpd service
    service: name=httpd state=started
  - name: deploy file
    copy: src={{src_path}}/index.html dest={{dest_path}}
    notify: restart httpd
  handlers:
  - name: restart httpd
    service: name=httpd state=restarted
 
